[package]
name = "stanu"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = "0.16"
num-derive = "0.4"
num-traits = "0.2"
rayon = "1.11"
walkdir = "2"
clap = { version = "4.5.58", features = ["derive"] }

[dev-dependencies]
expect-test = "1"
